### ISSUE TITLE
inconsistency in class naming

### ISSUE THREAD

**Issue by nj-io** [FACN3/APIKingsAndQueen#28]
small little mistake but nontheless:
```
<input id="search-query" type="text" class="searchquery">
            
            <button id="search-btn" class="search-btn">Search</button>
        </section>
```
keep the same naming structure "-" for your classes!

:hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil::hear_no_evil:

**Comment by sophiavocado** [comment]
fixed! @ionush
